name: dev

channels:
  - conda-forge

dependencies:
  - python
  - pip
  - jupyterlab
  - matplotlib
  - numpy
  - scipy
  - python-sounddevice
  - pip:
    - pyrtlsdr
    - pyrtlsdrlib